# Pre-commit hooks para Sistema POS O'data
# Instalar con: pre-commit install

repos:
  # Formateo de código Python
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3.13
        args: [--line-length=127]

  # Ordenamiento de imports
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=127]

  # Linting con flake8
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=127, --max-complexity=15, --ignore=E203,W503]
        additional_dependencies: [flake8-docstrings]

  # Verificación de tipos con mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --no-strict-optional]
        additional_dependencies: [types-requests, types-redis]

  # Hooks generales
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-merge-conflict
      - id: debug-statements

  # Seguridad con bandit
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: [--skip=B101,B601, --recursive, app/]

  # Análisis de complejidad
  - repo: https://github.com/rubik/xenon
    rev: v0.9.1
    hooks:
      - id: xenon
        args: [--max-average=B, --max-modules=B, --max-absolute=B, app/]

  # Hook personalizado para validar TODOs
  - repo: local
    hooks:
      - id: check-todos
        name: Check for excessive TODOs
        entry: python scripts/check_todos.py
        language: system
        files: \.py$
        pass_filenames: false

  # Hook personalizado para métricas de calidad
  - repo: local
    hooks:
      - id: code-quality-check
        name: Code Quality Check
        entry: python scripts/code_quality_monitor.py
        language: system
        pass_filenames: false
        stages: [manual]  # Solo ejecutar manualmente con --hook-stage manual