# Docker Compose Optimizado - Sistema POS Odata

services:
  # Base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: pos-odata-db
    environment:
      - POSTGRES_DB=pos_db_production
      - POSTGRES_USER=pos_user
      - POSTGRES_PASSWORD=4QRju1YLSF_gHOW9oRnxxg
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-production-db.sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - pos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pos_user -d pos_db_production"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Servidor Redis
  redis:
    image: redis:7-alpine
    container_name: pos-odata-redis
    command: redis-server --requirepass 4QRju1YLSF_gHOW9oRnxxg
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Aplicación Flask
  app:
    build: .
    container_name: pos-odata-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.main:app
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://pos_user:4QRju1YLSF_gHOW9oRnxxg@db:5432/pos_db_production
      - REDIS_URL=redis://:4QRju1YLSF_gHOW9oRnxxg@redis:6379/0
      - SECRET_KEY=TnrtknC2t6wlh_Be0CV59rumtGFZDszklYC8KW-PBFw
      - JWT_SECRET_KEY=f0aAvmIIAgDUxGj2fNMcajVTHM_-bDeU3h91nrYCi3AURHJws0z4rLlJWC7rkVE9GCyLGLgVoix67KM3N1yqag
    depends_on:
      - db
      - redis
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    networks:
      - pos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  pos-network:
    driver: bridge
