# Configuración de Prometheus para Sistema POS Sabrositas v2.0.0
# ================================================================
# Monitoreo multi-tienda enterprise con métricas avanzadas

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'sabrositas-pos'
    environment: 'production'

# Configuración de reglas de alertas
rule_files:
  - "/etc/prometheus/alerts.yml"

# Configuración de AlertManager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - sabrositas-alertmanager:9093

# Configuración de trabajos de scraping
scrape_configs:
  # Métricas de Prometheus mismo
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Métricas del sistema operativo
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['sabrositas-node-exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics

  # Métricas de contenedores Docker
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['sabrositas-cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics

  # Métricas de la aplicación POS
  - job_name: 'pos-app'
    static_configs:
      - targets: ['pos-app-production:8000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Métricas de PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['sabrositas-postgres-exporter:9187']
    scrape_interval: 30s
    metrics_path: /metrics

  # Métricas de Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['sabrositas-redis-exporter:9121']
    scrape_interval: 30s
    metrics_path: /metrics

  # Métricas de Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['pos-nginx-production:80']
    scrape_interval: 30s
    metrics_path: /nginx_status
    scrape_timeout: 10s

  # Monitoreo de endpoints con Blackbox
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://pos-app-production:8000/api/v1/health
        - http://pos-nginx-production:80/health
        - http://pos-app-production:8000/api/v1/stores
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: sabrositas-blackbox-exporter:9115

  # Monitoreo de servicios TCP
  - job_name: 'blackbox-tcp'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
        - pos-postgres-production:5432
        - pos-redis-production:6379
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: sabrositas-blackbox-exporter:9115

  # Métricas específicas por tienda (si están disponibles)
  - job_name: 'pos-store-metrics'
    static_configs:
      - targets: ['pos-app-production:8000']
    scrape_interval: 60s
    metrics_path: /api/v1/metrics/stores
    scrape_timeout: 30s

  # Métricas de rendimiento de la aplicación
  - job_name: 'pos-performance'
    static_configs:
      - targets: ['pos-app-production:8000']
    scrape_interval: 30s
    metrics_path: /api/v1/metrics/performance
    scrape_timeout: 15s

# Configuración de almacenamiento remoto (opcional para backup)
# remote_write:
#   - url: "http://remote-prometheus:9090/api/v1/write"
#     queue_config:
#       max_samples_per_send: 1000
#       max_shards: 200
#       capacity: 2500

# Configuración de lectura remota (opcional)
# remote_read:
#   - url: "http://remote-prometheus:9090/api/v1/read"